word_list = ["abruptly", "absurd", "abyss",
             "frizzled", "funny", "galaxy",
             "mnemonic", "matrix", "luxury",
             "syndrome", "subway", "mystify",
             "gossip", "nymph", "ovary",
             "voodoo", "waxy", "puzzling",
             "buzzwords", "jiujitsu", "haphazard",
             "squawk", "zipper", "zombie",
             "fixable", "razzmatazz", "disavow",
             "joking", "rhythm", "khaki",
             "sphinx", "knapsack", "fluffiness",
             "peekaboo", "voyeurism", "wellspring"]
